beethovenxfi/beethovenx-backend

- .ebextensions/nginx/conf.d/00_add_ratelimit.conf
- .ebextensions/nginx/conf.d/elasticbeanstalk/00_application.conf
> add rate limiting to nginx conf

- app/env.ts
- app/scheduleWorkerTasks.ts
- codegen.yml
- modules/pool/pool-sync.service.ts
- modules/pool/pool-sync.ts
- modules/subgraphs/balancer-subgraph/generated/balancer-subgraph-schema.graphql
- modules/subgraphs/balancer-subgraph/generated/balancer-subgraph-types.ts
- modules/subgraphs/beets-bar-subgraph/generated/beets-bar-subgraph-schema.graphql
- modules/subgraphs/beets-bar-subgraph/generated/beets-bar-subgraph-types.ts
- modules/subgraphs/blocks-subgraph/generated/blocks-subgraph-schema.graphql
- modules/subgraphs/blocks-subgraph/generated/blocks-subgraph-types.ts
- modules/subgraphs/changelog-subgraph/changelog-subgraph-queries.graphql
- modules/subgraphs/changelog-subgraph/changelog-subgraph.service.ts
- modules/subgraphs/changelog-subgraph/generated/changelog-subgraph-schema.graphql
- modules/subgraphs/changelog-subgraph/generated/changelog-subgraph-types.ts
- modules/subgraphs/masterchef-subgraph/generated/masterchef-subgraph-schema.graphql
- modules/subgraphs/masterchef-subgraph/generated/masterchef-subgraph-types.ts
Uses changelog subgraph to trigger pool updates
> Changelog integration

- app/scheduleWorkerTasks.ts
> add timeout to crons

- modules/subgraphs/blocks-subgraph/blocks-subgraph.service.ts
increase search window size to find block 24h ago
resolves #47
> double search window

- modules/pool/pool.gql
- modules/protocol/protocol.gql
- modules/protocol/protocol.resolvers.ts
- modules/protocol/protocol.service.ts
addresses #65 
also adds black_list filter to gqlpoolsquery
> Expose latest sync block

- modules/user/user.gql
- modules/user/user.resolvers.ts
- modules/user/user.service.ts
easy approach to fix request made in #69
> Sync user balance across all pools

- modules/pool/lib/pool-sync.service.ts
> Use contract events instead of changelog subgraph

- modules/pool/lib/apr-data-sources/fantom/stader-staked-ftm-apr.service.ts
- modules/pool/pool.prisma
- modules/pool/pool.service.ts
- prisma/migrations/20220815175959_add_apr_type/migration.sql
- prisma/schema.prisma
> add sftmx apr and add apr type

- modules/beets/beets.gql
- modules/beets/beets.resolvers.ts
- modules/beets/beets.service.ts
- modules/config/network-config.ts
- modules/token/lib/token-price-handlers/beets-price-handler.service.ts
- modules/token/lib/token-price.service.ts
- modules/token/token.service.ts
added endpoint:
```
query {
beetsGetBeetsPrice
}
```
Get price from on-chain through batchQuerySwap. Same for OP, using FTM vault. Integrated as priceHandler to update when all prices update.
> Beets price

- worker/job-handlers.ts
wanted to take a look at #61 but need better output for that. Are you ok with the changes?
> more meaningful log output

- worker/job-handlers.ts
- worker/worker.ts
> add custom sampling rates

- modules/pool/pool.service.ts
> Gql nullfield

- modules/token/lib/token-data-loader.service.ts
only add and remove what has changed
> Token whitelist management

- modules/user/lib/fantom/user-sync-masterchef-farm-balance.service.ts
- modules/user/lib/optimism/user-sync-gauge-balance.service.ts
- modules/user/lib/user-sync-wallet-balance.service.ts
- modules/user/user-types.ts
- modules/user/user.gql
- modules/user/user.resolvers.ts
- modules/user/user.service.ts
- worker/job-handlers.ts
- worker/scheduleLocalWorkerTasks.ts
those functions only sync the changed records. Unlike other sync functins.
> rename methods to align with function

- README.md
- env.local
- modules/pool/lib/pool-snapshot.service.ts
- modules/user/user.service.ts
> Prisma depricated

- modules/pool/lib/apr-data-sources/fantom/masterchef-farm-apr.service.ts
Take from DB as it already accounts for empty rewarder. Other option would be to have another RPC call, which seems more overhead.
> use rewards per second from DB

- worker/job-handlers.ts
> reduce sampling rate

- modules/config/network-config.ts
- modules/pool/lib/apr-data-sources/optimism/overnight-apr.service.ts
- modules/pool/lib/pool-gql-loader.service.ts
- modules/pool/pool.prisma
- modules/pool/pool.service.ts
- prisma/migrations/20221010164302_add_overnight_apr/migration.sql
- prisma/schema.prisma
- added support to display APR from Overnight's USD+ and DAI+
> add overnight APR

- modules/pool/lib/pool-gql-loader.service.ts
> fix apr display

- modules/pool/lib/apr-data-sources/optimism/overnight-apr.service.ts
> divide APR

- modules/user/lib/fantom/user-sync-masterchef-farm-balance.service.ts
- modules/user/lib/user-sync-wallet-balance.service.ts
- modules/user/user.service.ts
fbeets wallet and staking balance should have no poolId set. resolves #181
> Fix fbeets balance sync
